#![allow(missing_docs)]

use lerc_core::{BandLayout, BandSetView, MaskView, RasterView, Sample};
use lerc_writer::{encode, encode_band_set, EncodeOptions};

const BASELINE: &[u8] =
    include_bytes!("../../testdata/interoperability/writer-v0.4.3-refactor-baseline.bin");

struct BaselineBlobs {
    offset: usize,
}

impl BaselineBlobs {
    fn assert_next(&mut self, name: &str, actual: &[u8]) {
        let length_end = self.offset + std::mem::size_of::<u64>();
        let expected_len = u64::from_le_bytes(
            BASELINE[self.offset..length_end]
                .try_into()
                .expect("baseline length prefix is truncated"),
        ) as usize;
        let blob_end = length_end + expected_len;
        let expected = BASELINE
            .get(length_end..blob_end)
            .expect("baseline blob is truncated");
        assert_eq!(actual, expected, "encoded bytes changed for {name}");
        self.offset = blob_end;
    }

    fn finish(self) {
        assert_eq!(
            self.offset,
            BASELINE.len(),
            "baseline contains an untested trailing blob"
        );
    }
}

fn assert_type<T: Sample>(baseline: &mut BaselineBlobs, name: &str, max_z_error: f64) {
    const WIDTH: u32 = 16;
    const HEIGHT: u32 = 8;
    let pixels: Vec<T> = (0..(WIDTH * HEIGHT) as usize)
        .map(|index| T::from_f64(((index * 17 + index / 3) % 59) as f64))
        .collect();
    let mask_data: Vec<u8> = (0..(WIDTH * HEIGHT) as usize)
        .map(|index| u8::from(index % 5 != 0 && index % 11 != 0))
        .collect();
    let options = EncodeOptions::new()
        .with_max_z_error(max_z_error)
        .with_micro_block_size(8);
    let raster = RasterView::new(WIDTH, HEIGHT, 1, &pixels).unwrap();
    let mask = MaskView::new(WIDTH, HEIGHT, &mask_data).unwrap();
    baseline.assert_next(
        &format!("{name} all-valid"),
        &encode(raster, None, options).unwrap(),
    );
    baseline.assert_next(
        &format!("{name} masked"),
        &encode(raster, Some(mask), options).unwrap(),
    );
}

#[test]
fn refactors_preserve_v0_4_3_encoded_bytes() {
    // Generated by this matrix against the pre-refactor v0.4.3 source at
    // commit 4b83347. Cases whose specified behavior changed in v0.5 are
    // intentionally covered by the post-change snapshot in roundtrip.rs.
    let mut baseline = BaselineBlobs { offset: 0 };
    assert_type::<i8>(&mut baseline, "i8", 0.5);
    assert_type::<u8>(&mut baseline, "u8", 0.5);
    assert_type::<i16>(&mut baseline, "i16", 0.5);
    assert_type::<u16>(&mut baseline, "u16", 0.5);
    assert_type::<i32>(&mut baseline, "i32", 0.5);
    assert_type::<u32>(&mut baseline, "u32", 0.5);
    assert_type::<f32>(&mut baseline, "f32", 0.25);
    assert_type::<f64>(&mut baseline, "f64", 0.25);

    let huffman_pixels: Vec<u8> = (0..256)
        .map(|index| if index % 64 < 48 { 7 } else { 9 })
        .collect();
    baseline.assert_next(
        "u8 Huffman",
        &encode(
            RasterView::new(16, 16, 1, &huffman_pixels).unwrap(),
            None,
            EncodeOptions::new()
                .with_max_z_error(0.5)
                .with_micro_block_size(8),
        )
        .unwrap(),
    );

    let mut diff_pixels = Vec::new();
    for value in 0u16..8 {
        diff_pixels.push(value);
        diff_pixels.push(value);
    }
    baseline.assert_next(
        "u16 v5 diff",
        &encode(
            RasterView::new(4, 2, 2, &diff_pixels).unwrap(),
            None,
            EncodeOptions::new()
                .with_max_z_error(0.5)
                .with_micro_block_size(8),
        )
        .unwrap(),
    );

    let f64_pixels = vec![1.25f64, -2.5, 3.75, 4.5, -5.25, 6.0];
    baseline.assert_next(
        "f64 lossless",
        &encode(
            RasterView::new(3, 2, 1, &f64_pixels).unwrap(),
            None,
            EncodeOptions::new()
                .with_max_z_error(0.0)
                .with_micro_block_size(8),
        )
        .unwrap(),
    );

    let band_pixels: Vec<u16> = (0..3 * 8 * 4)
        .map(|index| ((index * 13 + index / 5) % 101) as u16)
        .collect();
    let band_mask: Vec<u8> = (0..8 * 4).map(|index| u8::from(index % 7 != 0)).collect();
    baseline.assert_next(
        "u16 band set",
        &encode_band_set(
            BandSetView::new(8, 4, 1, 3, BandLayout::Bsq, &band_pixels).unwrap(),
            Some(MaskView::new(8, 4, &band_mask).unwrap()),
            EncodeOptions::new()
                .with_max_z_error(0.5)
                .with_micro_block_size(8),
        )
        .unwrap(),
    );
    baseline.finish();
}
